name: test

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
    tags: ["v*"]

jobs:

  build:

    strategy:
      matrix:
        mpi: ['mpich', 'openmpi', 'intelmpi']
        os: ['ubuntu-latest', 'macos-latest']

    name: ${{ matrix.os }} ${{ matrix.mpi }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: install MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python dependencies
        run: |
          pip install numpy
          pip install scipy

      - name: build
        run: |
          cmake -S . -B build -DPRECISON=256 -DBUILD_TESTS=ON -DSMOKE=OFF
          cd build
          make
          cd ..

      - name: run tests
        run: |
          ./build/tests -d yes

      - name: test executables
        run: |
          mpiexec -n 2 ./build/hdspin -t 6 -N 128 -l EREM -b 2.4 -d gillespie --seed=123
          rm -r data grids
          mpiexec -n 2 ./build/hdspin -t 6 -N 128 -l EREM -b 2.2 -d standard --seed=123
          rm -r data grids
          mpiexec -n 10 ./build/hdspin -t 6 -N 128 -l EREM -b 2.3 --seed=123

      - name: run postprocess
        run: |
          python3 postprocess.py

